#Chat Application - Singidunum
#Tue Apr 14 10:04:48 CEST 2026
app.http=http\://localhost\:8080
app.ws=ws\://localhost\:8080/stomp
db.path=C\:\\Users\\student\\Desktop\\APP\\chat-storage.db
server.cert=cert/server.pem
user.cert=C\:\\Users\\student\\Desktop\\APP\\user.cert
user.key=cert/user.key
