#Chat Application - Singidunum
#Tue Mar 31 10:14:11 CEST 2026
app.ws=http\://localhost\:8080/stomp
db.path=C\:\\Users\\student\\Desktop\\APP\\chat-storage.db
server.cert=cert/server.pem
user.cert=C\:\\Users\\student\\Desktop\\APP\\user.cert
user.key=cert/user.key
